### ISSUE TITLE
Regarding Pull requests

### ISSUE THREAD

**Issue by nijuyonkadesu** [SVCE-ACM/A-December-of-Algorithms-2022#108]
Hello,
 I have noticed, for 2021 A-December-of-Algorithms, no pull requests were accepted. Is there any particular reason for doing it? Will the same trend be followed for 2022 as well ? 
 
Personally, I feel merging requests would make it easier for other users to quickly browse between different people's solution without struggle, rather than opeing each pull requests manually, which would discourage users to learn and explore. 
 
Furthermore, cloning the repository would lead to downloading bunch of empty folders with just `.gitignore` file, and it's counter intutive. 
 
Thank you.

**Comment by neha2127** [comment]
Hi
We will be merging the PR's eventually.
We will be doing it after the certificates have been sent to the participants who have sent a PR no later than the 15th of January, 2023.
