### ISSUE TITLE
what should be done

### ISSUE THREAD

**Issue by gowsrini2004** [SVCE-ACM/A-December-of-Algorithms-2022#15]
Heyy Hii!!
THE CHALLENGE IS GOINGG REALLY WELL

But, what should be done if i was not able to solve some dayyy
it the certificate based of like day 1 to day 10 or any 10 days of the challenge

**Comment by neha2127** [comment]
Hi
It's great to know that the challenge is going really for you.
The certificates will be awarded based on completion of all problems from day 1 to day 10, day 1 to day 21 and day 1 to day 31.
You have time to solve the problems till Jan 15th. So I suggest you don't give up and take your time and try to solve at least all the first 10 problems.

**Comment by neha2127** [comment]
Hi
It's great to know that the challenge is going really well for you.
The certificates will be awarded based on completion of all problems from day 1 to day 10, day 1 to day 21 and day 1 to day 31.
You have time to solve the problems till Jan 15th. So I suggest you don't give up and take your time and try to solve at least all the first 10 problems.
