### ISSUE TITLE
Day 11 

### ISSUE THREAD

**Issue by gowsrini2004** [SVCE-ACM/A-December-of-Algorithms-2022#19]
!! Another list is provided which contains the step that the monkey took Eg[1,1,2,1,2]. (from problem statment)

![image](https://user-images.githubusercontent.com/79265235/206870778-341037ca-0eb0-4cd1-9111-45a819ba19b1.png)

But That part had not been shown in the sample input
can you show the input for the above!!

**Comment by neha2127** [comment]
Hi
Thanks for letting us know. 
It was a typo and we will rectify it right away.
