### ISSUE TITLE
December 11 Lack of data

### ISSUE THREAD

**Issue by pravee42** [SVCE-ACM/A-December-of-Algorithms-2022#20]
![image](https://user-images.githubusercontent.com/65100038/206894878-4c1f63cf-3ce1-4e2c-be0b-128bb9e64221.png)

The array that has the steps made by the monkey is missing please check this out

**Comment by neha2127** [comment]
Hi
Thank you for pointing this out. 
It has been rectified.
Sorry for the confusion.
