### ISSUE TITLE
Sample Input/Output for Question 24 is correct?

### ISSUE THREAD

**Issue by souvikpal2000** [SVCE-ACM/A-December-of-Algorithms-2022#63]
As in Sample Input 1 
n = 1 which represents the length of the password
k = 2 which represents that each digit in password will either be 0 or 1 i.e, [0, k-1]

But the output is 
00, 01, 10 or 11
above password is of length 2

Same goes for Sample Input 2...

**Comment by neha2127** [comment]
The given sample input and output is correct. 
The question is a little bit complicated. So please take your time and read it once more. 
Please note that the output is NOT the password.

**Comment by souvikpal2000** [comment]
Then please elaborate in the explanation section with an Additional Input.
Thank You

**Comment by souvikpal2000** [comment]
> The given sample input and output is correct. The question is a little bit complicated. So please take your time and read it once more. Please note that the output is NOT the password.

Then please elaborate in the explanation section with an Additional Input.
Thank You

**Comment by neha2127** [comment]
We will take this suggestion and add another sample input and output.
