### ISSUE TITLE
2nd Sample Input of Question 28 looks wrong as per Question. 

### ISSUE THREAD

**Issue by souvikpal2000** [SVCE-ACM/A-December-of-Algorithms-2022#68]
In the Question it is written that Array must be in Sorted Order but in the Input it is not in Sorted Order

{ 3, 10, 12, 13, 15, 17, 21, **35**, 23 }

**Comment by souvikpal2000** [comment]
And the output is also wrong it must be 2.783

**Comment by neha2127** [comment]
There is no issue with the input and the output.
The line about the array being sorted was an error and we apologize for the confusion.

**Comment by souvikpal2000** [comment]
> There is no issue with the input and the output. The line about the array being sorted was an error and we apologize for the confusion.

So as you said, line about the array being sorted was an error. Their is also an error with the Output.
It will be 2.783 not 2.683.

**Calculation :-**
Sorted Array will we { 3, 10, 12, 13, 15, 17, 21, 23, 35 }
Total Time taken in seconds will be (10+3+12+3+13+3+15+3+17+3+21+3+23+3+35) = 167 seconds
Converting it to minutes will be (167/60) = 2.783 minutes

**Comment by neha2127** [comment]
The sum is actually 161 seconds.
But I understand the confusion. 
It is not necessary that the same person must move back and forth. This was the case only for the first sample and is puerly coincidental.
Keeping this in mind, the minimum time between 161 and 167 is 161.
I hope this clears it up.

**Comment by souvikpal2000** [comment]
> The sum is actually 161 seconds. But I understand the confusion. It is not necessary that the same person must move back and forth. This was the case only for the first sample and is purely coincidental. Keeping this in mind, the minimum time between 161 and 167 is 161. I hope this clears it up.

Can you tell the summation please how it comes 161. Please!!
Thank You

**Comment by neha2127** [comment]
Hi
Giving the calculation will give the answer to the problem. 
It is what you must figure out. 

The answer is 161 seconds which is equal to 2.683 minutes.
