### ISSUE TITLE
Output for Sample Input 2 for Question 29 looks wrong.

### ISSUE THREAD

**Issue by souvikpal2000** [SVCE-ACM/A-December-of-Algorithms-2022#72]
Input = {1, 4, 3, 6, 2, 1, 8, 1, 3, 7, 7}

After distributing Candies it will be {1, 2, 1, 3, 2, 1, 2, 1, 2, 3, 1}

Minimum Candies will be 19

**Comment by neha2127** [comment]
Hi
Yes. We are aware. We had made the changes just a few minutes ago.
Please let us know if the change has not been reflected as of yet.

Thank you!
