### ISSUE TITLE
doubt on explanation of day25

### ISSUE THREAD

**Issue by GREEDnim** [SVCE-ACM/A-December-of-Algorithms-2022#80]
for this question, [day 25](https://github.com/SVCE-ACM/A-December-of-Algorithms-2022#december-25---the-motorbike-race) , what does this mean in the explanation 

 [  The i-th line in the next N lines contains two numbers, v and x, which are the velocity and the current position of the i-th motorcyclist (1 <= v, x <= 100,000). ](https://github.com/SVCE-ACM/A-December-of-Algorithms-2022#explanation-22)

if there are only n motorcycles, how is x>n in the testcases?

**Comment by krithika-2111** [comment]
Only n motorcycles exist, yet there are x positions. This indicates that the test cases are based on an analysis. As a result, x> n.
